social:
  'facebook.com': 'Facebook'
  'fb.me': 'Facebook'
  'qzone.qq.com': 'Qzone'
  'habbo.com': 'Haboo'
  'twitter.com': 'Twitter'
  't.co': 'Twitter'
  'renren.com': 'Renren'
  'login.live.com': 'Windows Live Spaces'
  'linkedin.com': 'LinkedIn'
  'bebo.com': 'Bebo'
  'vk.com': 'Vkontakte'
  'vkontakte.ru': 'Vkontakte'
  'login.tagged.com': 'Tagged'
  'orkut.com': 'Orkut'
  'myspace.com': 'Myspace'
  'friendster.com': 'Friendster'
  'badoo.com': 'Badoo'
  'hi5.com': 'hi5'
  'netlog.com': 'Netlog'
  'flixster.com': 'Flixster'
  'mylife.ru': 'MyLife'
  'classmates.com': 'Classmates.com'
  'github.com': 'Github'
  'url.google.com': 'Google Plus'
  'douban.com': 'douban'
  'odnoklassniki.ru': 'Odnoklassniki'
  'viadeo.com': 'Viadeo'
  'flickr.com': 'Flickr'
  'weeworld.com': 'WeeWorld'
  'last.fm': 'Last.fm'
  'lastfm.ru': 'Last.fm'
  'lastfm.de': 'Last.fm'
  'lastfm.es': 'Last.fm'
  'lastfm.fr': 'Last.fm'
  'lastfm.it': 'Last.fm'
  'lastfm.jp': 'Last.fm'
  'lastfm.pl': 'Last.fm'
  'lastfm.com.br': 'Last.fm'
  'lastfm.se': 'Last.fm'
  'lastfm.com.tr': 'Last.fm'
  'myheritage.com': 'MyHeritage'
  'xanga.com': 'Xanga'
  'mixi.jp': 'Mixi'
  'global.cyworld.com': 'Cyworld'
  'gaiaonline.com': 'Gaia Online'
  'skyrock.com': 'Skyrock'
  'blackplanet.com': 'BlackPlanet'
  'myyearbook.com': 'myYearbook'
  'fotolog.com': 'Fotolog'
  'friendsreunited.com': 'Friends Reunited'
  'livejournal.ru': 'LiveJournal'
  'livejournal.com': 'LiveJournal'
  'studivz.net': 'StudiVZ'
  'meinvz.net': 'MeinVZ'
  'stackoverflow.com': 'StackOverflow'
  'sonico.com': 'Sonico.com'
  'pinterest.com': 'Pinterest'
  'plaxo.com': 'Plaxo'
  'geni.com': 'Geni.com'
  'tuenti.com': 'Tuenti'
  'xing.com': 'XING'
  'taringa.net': 'Taringa!'
  'nk.pl': 'Nasza-klasa.pl'
  'stumbleupon.com': 'StumbleUpon'
  'sourceforge.net': 'SourceForge'
  'hyves.nl': 'Hyves'
  'wayn.com': 'WAYN'
  'buzznet.com': 'Buzznet'
  'multiply.com': 'Multiply'
  'foursquare.com': 'Foursquare'
  'vkrugudruzei.ru': 'vkrugudruzei.ru'
  'my.mail.ru': 'my.mail.ru'
  'moikrug.ru': 'moikrug.ru'
  'reddit.com': 'reddit'
  'news.ycombinator.com': 'Hacker News'
  'identi.ca': 'identi.ca'
  'weibo.com': 'Weibo'
  't.cn': 'Weibo'
  'youtube.com': 'YouTube'
  'youtu.be': 'YouTube'
  'vimeo.com': 'Vimeo'
  'tumblr.com': 'tumblr'
search:
  "xunda": "dunha"